name: pipeline
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: apps/web
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Install pnpm
              uses: pnpm/action-setup@v6
              with:
                  version: 10

            - name: Setup Nodejs
              uses: actions/setup-node@v5
              with:
                  node-version: "22"
                  cache: "pnpm"
                  cache-dependency-path: apps/web/pnpm-lock.yaml

            - name: Install
              run: |
                  pnpm install --frozen-lockfile

            - name: Build Artifact
              run: NODE_OPTIONS="--max-old-space-size=4096" pnpm run build
